Add MacOSXWatchService
sbt/io pull request #138
Opened 2018-03-29 00:07 UTC by eatkins

This watch service is taken from my CloseWatch plugin, found at
https://github.com/swoval/swoval

It uses a native jni library, provided by apple-file-events, to receive
file events from the os. I more or less copied this file from the close
watch source code with some minor modifications given that it is now in
the sbt.io package.

2018-03-29 00:08 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.1.x&zinc=1.1.x&io=pull/138/head&librarymanagement=1.1.x&util=1.1.x&website=1.1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

2018-03-29 15:31 UTC, eed3si9n requested changes
Travis CI failed for Scala 2.10. Probably need to make small adjustments to supply type annotation or sugar.

2018-03-29 15:31 UTC, eed3si9n commented on io/src/main/scala/sbt/io/MacOSXWatchService.scala
> +  private[this] val watcher: FileEventsApi = FileEventsApi.apply(onFileEvent, _ => {})
This failed compilation on Travis for 2.10:

```scala
[error] /home/travis/build/sbt/io/io/src/main/scala/sbt/io/MacOSXWatchService.scala:21:66: missing arguments for method onFileEvent in class MacOSXWatchService;
[error] follow this method with `_' if you want to treat it as a partially applied function
[error]   private[this] val watcher: FileEventsApi = FileEventsApi.apply(onFileEvent, _ => {})
[error]                                                                  ^
```

2018-03-29 15:31 UTC, eed3si9n commented on io/src/main/scala/sbt/io/MacOSXWatchService.scala
> +    executor.submit((() => {
```scala
[error] /home/travis/build/sbt/io/io/src/main/scala/sbt/io/MacOSXWatchService.scala:61:25: type mismatch;
[error]  found   : () => Unit
[error]  required: Runnable
[error]     executor.submit((() => {
[error]                         ^
```

2018-03-29 18:03 UTC, eatkins commented
I made the file 2.10 compatible, but, out of curiosity, why do we build for 2.10 (and 2.11)? Isn't this module only used by sbt 1.x?

2018-03-29 18:18 UTC, eed3si9n commented
> I made the file 2.10 compatible, but, out of curiosity, why do we build for 2.10 (and 2.11)? Isn't this module only used by sbt 1.x?

We first split out IO as an aspirational general-purpose IO module while we were still in 0.13, and built other things on top of that. At some point we might drop 2.10.

2018-03-29 18:19 UTC, eed3si9n approved these changes

2018-04-03 15:59 UTC, dwijnand approved these changes
thanks @eatkins

2018-04-03 15:59 UTC, merged