Add helper methods to create mappings
sbt/io pull request #38
Opened 2017-03-02 16:47 UTC by muuki88

- directory: create mappings from a baseDirectory including the baseDirectory
- contentOf: create mappings from a baseDirectory excluding the baseDirectory

I put this on the `Path` object. Not sure if this is a good place.
The test aren't property based. I probably need to add some corner cases like

- [ ] empty `baseDirectory`
- [ ] if `baseDirectory` is a file
- [ ] non-existing `baseDirectory`

2017-03-02 22:10 UTC, dwijnand requested changes
I've a few comments, but also I think this should probably live with its brothers in `Mapper` (PathMapper.scala).

Thank you for taking the time to PR!

2017-03-02 22:10 UTC, dwijnand commented on io/src/main/scala/sbt/io/Path.scala
> +   *   case (src, destination => src -> s"new/path/$destination"
this example doesn't compile (missing `)`) and is missing an explanation at the end.

2017-03-02 22:10 UTC, dwijnand commented on io/src/main/scala/sbt/io/Path.scala
> +   * }}}
This example seems to be wrong. I'm getting:

```scala
scala> for ((file, path) <- Path directory (file("base") / "extra")) println(s"""$file -> "$path"""")
base/extra -> "extra"
base/extra/file1 -> "extra/file1"
base/extra/file2 -> "extra/file2"
```

2017-03-02 22:10 UTC, dwijnand commented on io/src/main/scala/sbt/io/Path.scala
> +   * }}}
This example seems to be wrong. I'm getting:

```scala
scala> for ((file, path) <- Path contentOf (file("base") / "extra")) println(s"""$file -> "$path"""")
base/extra/file1 -> "file1"
base/extra/file2 -> "file2"
```

2017-03-18 19:58 UTC, eed3si9n commented
@dwijnand What's the status on this PR?

2017-03-18 20:55 UTC, dwijnand commented on io/src/main/scala/sbt/io/PathMapper.scala
> +   * }}}
Isn't this still missing `$baseDirectory/extra -> "extra"`?

2017-03-18 20:55 UTC, dwijnand commented on io/src/main/scala/sbt/io/PathMapper.scala
> +   * File($baseDirectory/extras/file2) -> "extras/"file2"
there's an extra `"`

2017-03-18 20:55 UTC, dwijnand commented on io/src/main/scala/sbt/io/PathMapper.scala
> +   *   case (src, destination => src -> s"new/path/$destination"
there's still a missing `)` here

2017-03-18 20:56 UTC, dwijnand commented
I just submitted the review that I had pending from 2 weeks ago..

Haven't reviewed the latest 2 commits.

2017-03-24 16:57 UTC, muuki88 commented
Sorry for the long standing PR. Finally got time to clean this up

2017-03-27 18:01 UTC, eed3si9n approved these changes

2017-03-28 10:53 UTC, dwijnand approved these changes
Thanks Muki!

2017-03-28 10:53 UTC, merged